// Generated by tools/build_assets.py from the screen designs. Do not edit.
#pragma once

static const uint16_t LABEL_X_0[] PROGMEM = {50, 119, 232, 318, 393};

static const char LABEL_TEXT_0[] PROGMEM = "Status\0S.P.E.C.I.A.L.\0Skills\0Perks\0General";

static const uint16_t LABEL_X_1[] PROGMEM = {50, 140, 240, 320, 400};

static const char LABEL_TEXT_1[] PROGMEM = "Weapons\0Apparel\0Aid\0Misc\0Ammo";

static const uint16_t LABEL_X_2[] PROGMEM = {50, 149, 247, 327, 400};

static const char LABEL_TEXT_2[] PROGMEM = "Local Map\0World Map\0Quests\0Notes\0Radio";
